POST http://localhost:5284/receipts/process
Content-Type: application/json

{
  "retailer": "Walgreens",
  "purchaseDate": "2022-01-02",
  "purchaseTime": "08:13",
  "total": "2.65",
  "items": [
    {"shortDescription": "Pepsi - 12-oz", "price": "1.25"},
    {"shortDescription": "Dasani", "price": "1.40"}
  ]
}

> {% client.global.set("added_guid_morning", response.body.id); %}

###

GET http://localhost:5284/receipts/{{added_guid_morning}}/points
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function() {
        let type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("Correct points returned", function() {
        let points = response.body.points;
        client.assert(15 == points, "Expected 15 points but received '" + points + "'");
    });
%}